// @ts-nocheck
// This is a placeholder file to satisfy TypeScript.
// The actual file is generated by Wails.
// This proxy will return a dummy function for any property access.
const handler = {
  get: function(target: any, prop: any, receiver: any) {
    if (prop === 'then') {
      return undefined;
    }
    return () => Promise.resolve();
  }
};

export const ExportContext = new Proxy({}, handler);
export const ReadFileContent = new Proxy({}, handler);
export const GetFileStats = new Proxy({}, handler);
export const GetRecentProjects = new Proxy({}, handler);
export const AddRecentProject = new Proxy({}, handler);
export const RemoveRecentProject = new Proxy({}, handler);
export const SelectDirectory = new Proxy({}, handler);
export const GetCurrentDirectory = new Proxy({}, handler);
export const ListFiles = new Proxy({}, handler);
export const BuildContext = new Proxy({}, handler);
export const BuildContextFromRequest = new Proxy({}, handler);
export const GetContext = new Proxy({}, handler);
export const DeleteContext = new Proxy({}, handler);
export const GetProjectContexts = new Proxy({}, handler);
export const SuggestContextFiles = new Proxy({}, handler);
export const GenerateCode = new Proxy({}, handler);
export const GenerateIntelligentCode = new Proxy({}, handler);
export const ListAvailableModels = new Proxy({}, handler);
export const GetProviderInfo = new Proxy({}, handler);
export const AnalyzeProject = new Proxy({}, handler);
export const AnalyzeFile = new Proxy({}, handler);
export const DetectLanguages = new Proxy({}, handler);
export const GetSupportedAnalyzers = new Proxy({}, handler);
export const GetUncommittedFiles = new Proxy({}, handler);
export const GetBranches = new Proxy({}, handler);
export const GetCurrentBranch = new Proxy({}, handler);
export const GetRichCommitHistory = new Proxy({}, handler);
export const IsGitAvailable = new Proxy({}, handler);
export const GetSettings = new Proxy({}, handler);
export const SaveSettings = new Proxy({}, handler);
export const RunTests = new Proxy({}, handler);
export const DiscoverTests = new Proxy({}, handler);
export const Build = new Proxy({}, handler);
export const TypeCheck = new Proxy({}, handler);
export const GenerateDiff = new Proxy({}, handler);
export const ApplyEdits = new Proxy({}, handler);
export const ApplySingleEdit = new Proxy({}, handler);
export const GenerateReport = new Proxy({}, handler);
export const ListReports = new Proxy({}, handler);
export const GetReport = new Proxy({}, handler);
export const ExportProject = new Proxy({}, handler);
export const ExecuteTaskProtocol = new Proxy({}, handler);
export const GetTaskProtocolConfiguration = new Proxy({}, handler);
export const ValidatePath = new Proxy({}, handler);
export const GetGuardrailPolicies = new Proxy({}, handler);
export const GetBudgetPolicies = new Proxy({}, handler);
