// This is a placeholder file to satisfy TypeScript.
// The actual file is generated by Wails.
export namespace domain {
  export type FileNode = any;
  export type ContextBuildOptions = any;
  export type ContextSummaryInfo = any;
  export type ExportResult = any;
  export type StaticAnalysisReport = any;
  export type StaticAnalysisResult = any;
  export type StaticAnalyzerType = any;
  export type FileStatus = any;
  export type CommitWithFiles = any;
  export type SettingsDTO = any;
  export type TestConfig = any;
  export type TestResult = any;
  export type TestSuite = any;
  export type BuildResult = any;
  export type TypeCheckResult = any;
  export type DiffFormat = any;
  export type DiffResult = any;
  export type EditsJSON = any;
  export type ApplyResult = any;
  export type Edit = any;
  export type GuardrailViolation = any;
  export type GuardrailPolicy = any;
  export type BudgetPolicy = any;
}
