// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBudgetPolicy(arg1) {
  return window['go']['main']['App']['AddBudgetPolicy'](arg1);
}

export function AddGuardrailPolicy(arg1) {
  return window['go']['main']['App']['AddGuardrailPolicy'](arg1);
}

export function AddRecentProject(arg1, arg2) {
  return window['go']['main']['App']['AddRecentProject'](arg1, arg2);
}

export function AddRepairRule(arg1) {
  return window['go']['main']['App']['AddRepairRule'](arg1);
}

export function AddToGitignore(arg1, arg2) {
  return window['go']['main']['App']['AddToGitignore'](arg1, arg2);
}

export function AnalyzeFile(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeFile'](arg1, arg2);
}

export function AnalyzeGoProject(arg1) {
  return window['go']['main']['App']['AnalyzeGoProject'](arg1);
}

export function AnalyzeJavaScriptProject(arg1) {
  return window['go']['main']['App']['AnalyzeJavaScriptProject'](arg1);
}

export function AnalyzeProject(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeProject'](arg1, arg2);
}

export function AnalyzeTaskAndCollectContext(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnalyzeTaskAndCollectContext'](arg1, arg2, arg3);
}

export function AnalyzeTypeScriptProject(arg1) {
  return window['go']['main']['App']['AnalyzeTypeScriptProject'](arg1);
}

export function ApplyEdits(arg1) {
  return window['go']['main']['App']['ApplyEdits'](arg1);
}

export function ApplySingleEdit(arg1) {
  return window['go']['main']['App']['ApplySingleEdit'](arg1);
}

export function Build(arg1, arg2) {
  return window['go']['main']['App']['Build'](arg1, arg2);
}

export function BuildAffectedGraph(arg1, arg2) {
  return window['go']['main']['App']['BuildAffectedGraph'](arg1, arg2);
}

export function BuildAndTypeCheck(arg1, arg2) {
  return window['go']['main']['App']['BuildAndTypeCheck'](arg1, arg2);
}

export function BuildContext(arg1, arg2, arg3) {
  return window['go']['main']['App']['BuildContext'](arg1, arg2, arg3);
}

export function BuildContextAtRef(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BuildContextAtRef'](arg1, arg2, arg3, arg4);
}

export function BuildContextFromRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['BuildContextFromRequest'](arg1, arg2, arg3);
}

export function BuildContextLegacy() {
  return window['go']['main']['App']['BuildContextLegacy']();
}

export function BuildSymbolGraph(arg1, arg2) {
  return window['go']['main']['App']['BuildSymbolGraph'](arg1, arg2);
}

export function CancelAutonomousTask(arg1) {
  return window['go']['main']['App']['CancelAutonomousTask'](arg1);
}

export function CheckoutBranch(arg1, arg2) {
  return window['go']['main']['App']['CheckoutBranch'](arg1, arg2);
}

export function CheckoutCommit(arg1, arg2) {
  return window['go']['main']['App']['CheckoutCommit'](arg1, arg2);
}

export function CleanupTempFiles(arg1) {
  return window['go']['main']['App']['CleanupTempFiles'](arg1);
}

export function CleanupTempRepository(arg1) {
  return window['go']['main']['App']['CleanupTempRepository'](arg1);
}

export function CloneRepository(arg1) {
  return window['go']['main']['App']['CloneRepository'](arg1);
}

export function CloseStreamingContext(arg1) {
  return window['go']['main']['App']['CloseStreamingContext'](arg1);
}

export function CreateStreamingContext(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateStreamingContext'](arg1, arg2, arg3);
}

export function CreateTaskProtocolForProject(arg1, arg2) {
  return window['go']['main']['App']['CreateTaskProtocolForProject'](arg1, arg2);
}

export function DeleteContext(arg1) {
  return window['go']['main']['App']['DeleteContext'](arg1);
}

export function DeleteReport(arg1) {
  return window['go']['main']['App']['DeleteReport'](arg1);
}

export function DeleteUXReport(arg1) {
  return window['go']['main']['App']['DeleteUXReport'](arg1);
}

export function DetectLanguages(arg1) {
  return window['go']['main']['App']['DetectLanguages'](arg1);
}

export function DiscoverTests(arg1, arg2) {
  return window['go']['main']['App']['DiscoverTests'](arg1, arg2);
}

export function ExecuteRepair(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteRepair'](arg1, arg2, arg3, arg4);
}

export function ExecuteTask(arg1) {
  return window['go']['main']['App']['ExecuteTask'](arg1);
}

export function ExecuteTaskProtocol(arg1) {
  return window['go']['main']['App']['ExecuteTaskProtocol'](arg1);
}

export function ExecuteTaskflow() {
  return window['go']['main']['App']['ExecuteTaskflow']();
}

export function ExportContext(arg1) {
  return window['go']['main']['App']['ExportContext'](arg1);
}

export function ExportProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportProject'](arg1, arg2, arg3);
}

export function ExportReport(arg1, arg2) {
  return window['go']['main']['App']['ExportReport'](arg1, arg2);
}

export function GenerateAndPublishDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateAndPublishDiff'](arg1, arg2, arg3);
}

export function GenerateCode(arg1, arg2) {
  return window['go']['main']['App']['GenerateCode'](arg1, arg2);
}

export function GenerateCodeStream(arg1, arg2) {
  return window['go']['main']['App']['GenerateCodeStream'](arg1, arg2);
}

export function GenerateCodeWithOptions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateCodeWithOptions'](arg1, arg2, arg3);
}

export function GenerateComplianceReport(arg1, arg2) {
  return window['go']['main']['App']['GenerateComplianceReport'](arg1, arg2);
}

export function GenerateDerivedDiffReport(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateDerivedDiffReport'](arg1, arg2, arg3);
}

export function GenerateDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateDiff'](arg1, arg2, arg3);
}

export function GenerateDiffFromEdits(arg1, arg2) {
  return window['go']['main']['App']['GenerateDiffFromEdits'](arg1, arg2);
}

export function GenerateDiffFromResults(arg1, arg2) {
  return window['go']['main']['App']['GenerateDiffFromResults'](arg1, arg2);
}

export function GenerateIntelligentCode(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateIntelligentCode'](arg1, arg2, arg3);
}

export function GeneratePerformanceMetrics(arg1) {
  return window['go']['main']['App']['GeneratePerformanceMetrics'](arg1);
}

export function GenerateReport(arg1, arg2) {
  return window['go']['main']['App']['GenerateReport'](arg1, arg2);
}

export function GenerateSBOM(arg1, arg2) {
  return window['go']['main']['App']['GenerateSBOM'](arg1, arg2);
}

export function GenerateTimeToGreenMetrics(arg1) {
  return window['go']['main']['App']['GenerateTimeToGreenMetrics'](arg1);
}

export function GenerateWhyViewReport(arg1, arg2) {
  return window['go']['main']['App']['GenerateWhyViewReport'](arg1, arg2);
}

export function GetAutonomousTaskStatus(arg1) {
  return window['go']['main']['App']['GetAutonomousTaskStatus'](arg1);
}

export function GetAvailableRepairRules(arg1) {
  return window['go']['main']['App']['GetAvailableRepairRules'](arg1);
}

export function GetBranches(arg1) {
  return window['go']['main']['App']['GetBranches'](arg1);
}

export function GetBudgetPolicies() {
  return window['go']['main']['App']['GetBudgetPolicies']();
}

export function GetCommitHistory(arg1, arg2) {
  return window['go']['main']['App']['GetCommitHistory'](arg1, arg2);
}

export function GetContext(arg1) {
  return window['go']['main']['App']['GetContext'](arg1);
}

export function GetContextContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetContextContent'](arg1, arg2, arg3);
}

export function GetContextLines(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetContextLines'](arg1, arg2, arg3);
}

export function GetCurrentBranch(arg1) {
  return window['go']['main']['App']['GetCurrentBranch'](arg1);
}

export function GetCurrentDirectory() {
  return window['go']['main']['App']['GetCurrentDirectory']();
}

export function GetCustomIgnoreRules() {
  return window['go']['main']['App']['GetCustomIgnoreRules']();
}

export function GetExportHistory(arg1) {
  return window['go']['main']['App']['GetExportHistory'](arg1);
}

export function GetFileAtRef(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFileAtRef'](arg1, arg2, arg3);
}

export function GetFileContentAtCommit(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFileContentAtCommit'](arg1, arg2, arg3);
}

export function GetFileStats(arg1) {
  return window['go']['main']['App']['GetFileStats'](arg1);
}

export function GetFullContextContent(arg1) {
  return window['go']['main']['App']['GetFullContextContent'](arg1);
}

export function GetGitignoreContent(arg1) {
  return window['go']['main']['App']['GetGitignoreContent'](arg1);
}

export function GetGitignoreContentForProject(arg1) {
  return window['go']['main']['App']['GetGitignoreContentForProject'](arg1);
}

export function GetGuardrailPolicies() {
  return window['go']['main']['App']['GetGuardrailPolicies']();
}

export function GetMetricsSummary() {
  return window['go']['main']['App']['GetMetricsSummary']();
}

export function GetProjectContexts(arg1) {
  return window['go']['main']['App']['GetProjectContexts'](arg1);
}

export function GetProviderInfo() {
  return window['go']['main']['App']['GetProviderInfo']();
}

export function GetReadyTasks() {
  return window['go']['main']['App']['GetReadyTasks']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function GetRemoteBranches(arg1) {
  return window['go']['main']['App']['GetRemoteBranches'](arg1);
}

export function GetReport(arg1) {
  return window['go']['main']['App']['GetReport'](arg1);
}

export function GetRichCommitHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetRichCommitHistory'](arg1, arg2, arg3);
}

export function GetSLAPolicy() {
  return window['go']['main']['App']['GetSLAPolicy']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStreamingContext(arg1) {
  return window['go']['main']['App']['GetStreamingContext'](arg1);
}

export function GetSupportedAnalyzers() {
  return window['go']['main']['App']['GetSupportedAnalyzers']();
}

export function GetSupportedSBOMFormats() {
  return window['go']['main']['App']['GetSupportedSBOMFormats']();
}

export function GetSymbolDependencies(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSymbolDependencies'](arg1, arg2, arg3);
}

export function GetSymbolDependents(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSymbolDependents'](arg1, arg2, arg3);
}

export function GetSymbolSuggestions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSymbolSuggestions'](arg1, arg2, arg3);
}

export function GetTaskDependencies(arg1) {
  return window['go']['main']['App']['GetTaskDependencies'](arg1);
}

export function GetTaskLogs(arg1) {
  return window['go']['main']['App']['GetTaskLogs'](arg1);
}

export function GetTaskProtocolConfiguration(arg1, arg2) {
  return window['go']['main']['App']['GetTaskProtocolConfiguration'](arg1, arg2);
}

export function GetTaskStatus(arg1) {
  return window['go']['main']['App']['GetTaskStatus'](arg1);
}

export function GetTaskflowProgress() {
  return window['go']['main']['App']['GetTaskflowProgress']();
}

export function GetUXReport(arg1) {
  return window['go']['main']['App']['GetUXReport'](arg1);
}

export function GetUXReports(arg1) {
  return window['go']['main']['App']['GetUXReports'](arg1);
}

export function GetUncommittedFiles(arg1) {
  return window['go']['main']['App']['GetUncommittedFiles'](arg1);
}

export function GitHubBuildContext(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitHubBuildContext'](arg1, arg2, arg3);
}

export function GitHubGetBranches(arg1) {
  return window['go']['main']['App']['GitHubGetBranches'](arg1);
}

export function GitHubGetCommits(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitHubGetCommits'](arg1, arg2, arg3);
}

export function GitHubGetDefaultBranch(arg1) {
  return window['go']['main']['App']['GitHubGetDefaultBranch'](arg1);
}

export function GitHubGetFileContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitHubGetFileContent'](arg1, arg2, arg3);
}

export function GitHubListFiles(arg1, arg2) {
  return window['go']['main']['App']['GitHubListFiles'](arg1, arg2);
}

export function GitLabBuildContext(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitLabBuildContext'](arg1, arg2, arg3);
}

export function GitLabGetBranches(arg1) {
  return window['go']['main']['App']['GitLabGetBranches'](arg1);
}

export function GitLabGetCommits(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitLabGetCommits'](arg1, arg2, arg3);
}

export function GitLabGetDefaultBranch(arg1) {
  return window['go']['main']['App']['GitLabGetDefaultBranch'](arg1);
}

export function GitLabGetFileContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitLabGetFileContent'](arg1, arg2, arg3);
}

export function GitLabListFiles(arg1, arg2) {
  return window['go']['main']['App']['GitLabListFiles'](arg1, arg2);
}

export function IsGitAvailable() {
  return window['go']['main']['App']['IsGitAvailable']();
}

export function IsGitHubURL(arg1) {
  return window['go']['main']['App']['IsGitHubURL'](arg1);
}

export function IsGitLabURL(arg1) {
  return window['go']['main']['App']['IsGitLabURL'](arg1);
}

export function IsGitRepository(arg1) {
  return window['go']['main']['App']['IsGitRepository'](arg1);
}

export function ListAutonomousTasks(arg1) {
  return window['go']['main']['App']['ListAutonomousTasks'](arg1);
}

export function ListAvailableModels() {
  return window['go']['main']['App']['ListAvailableModels']();
}

export function ListFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2, arg3);
}

export function ListFilesAtRef(arg1, arg2) {
  return window['go']['main']['App']['ListFilesAtRef'](arg1, arg2);
}

export function ListReports(arg1) {
  return window['go']['main']['App']['ListReports'](arg1);
}

export function LoadTasks() {
  return window['go']['main']['App']['LoadTasks']();
}

export function PauseTask(arg1) {
  return window['go']['main']['App']['PauseTask'](arg1);
}

export function PublishDiff(arg1) {
  return window['go']['main']['App']['PublishDiff'](arg1);
}

export function QwenExecuteTask(arg1) {
  return window['go']['main']['App']['QwenExecuteTask'](arg1);
}

export function QwenGetAvailableModels() {
  return window['go']['main']['App']['QwenGetAvailableModels']();
}

export function QwenPreviewContext(arg1) {
  return window['go']['main']['App']['QwenPreviewContext'](arg1);
}

export function ReadFileContent(arg1, arg2) {
  return window['go']['main']['App']['ReadFileContent'](arg1, arg2);
}

export function RefreshAIModels(arg1, arg2) {
  return window['go']['main']['App']['RefreshAIModels'](arg1, arg2);
}

export function RemoveBudgetPolicy(arg1) {
  return window['go']['main']['App']['RemoveBudgetPolicy'](arg1);
}

export function RemoveGuardrailPolicy(arg1) {
  return window['go']['main']['App']['RemoveGuardrailPolicy'](arg1);
}

export function RemoveRecentProject(arg1) {
  return window['go']['main']['App']['RemoveRecentProject'](arg1);
}

export function RemoveRepairRule(arg1) {
  return window['go']['main']['App']['RemoveRepairRule'](arg1);
}

export function RequestShotgunContextGeneration(arg1, arg2) {
  return window['go']['main']['App']['RequestShotgunContextGeneration'](arg1, arg2);
}

export function RequestTaskProtocolCorrectionGuidance(arg1, arg2) {
  return window['go']['main']['App']['RequestTaskProtocolCorrectionGuidance'](arg1, arg2);
}

export function ResetTaskflow() {
  return window['go']['main']['App']['ResetTaskflow']();
}

export function ResumeTask(arg1) {
  return window['go']['main']['App']['ResumeTask'](arg1);
}

export function RollbackEdits(arg1) {
  return window['go']['main']['App']['RollbackEdits'](arg1);
}

export function RunIntegrationTests(arg1, arg2) {
  return window['go']['main']['App']['RunIntegrationTests'](arg1, arg2);
}

export function RunSmokeTests(arg1, arg2) {
  return window['go']['main']['App']['RunSmokeTests'](arg1, arg2);
}

export function RunTargetedTests(arg1, arg2) {
  return window['go']['main']['App']['RunTargetedTests'](arg1, arg2);
}

export function RunTests(arg1) {
  return window['go']['main']['App']['RunTests'](arg1);
}

export function RunUnitTests(arg1, arg2) {
  return window['go']['main']['App']['RunUnitTests'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveUXReport(arg1) {
  return window['go']['main']['App']['SaveUXReport'](arg1);
}

export function ScanLicenses(arg1) {
  return window['go']['main']['App']['ScanLicenses'](arg1);
}

export function ScanVulnerabilities(arg1) {
  return window['go']['main']['App']['ScanVulnerabilities'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetSLAPolicy(arg1) {
  return window['go']['main']['App']['SetSLAPolicy'](arg1);
}

export function StartAutonomousTask(arg1) {
  return window['go']['main']['App']['StartAutonomousTask'](arg1);
}

export function StartFileWatcher(arg1) {
  return window['go']['main']['App']['StartFileWatcher'](arg1);
}

export function StopFileWatcher() {
  return window['go']['main']['App']['StopFileWatcher']();
}

export function SuggestContextFiles(arg1, arg2) {
  return window['go']['main']['App']['SuggestContextFiles'](arg1, arg2);
}

export function TestBackend(arg1, arg2) {
  return window['go']['main']['App']['TestBackend'](arg1, arg2);
}

export function TestIgnoreRules(arg1, arg2) {
  return window['go']['main']['App']['TestIgnoreRules'](arg1, arg2);
}

export function TypeCheck(arg1, arg2) {
  return window['go']['main']['App']['TypeCheck'](arg1, arg2);
}

export function UpdateBudgetPolicy(arg1) {
  return window['go']['main']['App']['UpdateBudgetPolicy'](arg1);
}

export function UpdateCustomIgnoreRules(arg1) {
  return window['go']['main']['App']['UpdateCustomIgnoreRules'](arg1);
}

export function UpdateGuardrailPolicy(arg1) {
  return window['go']['main']['App']['UpdateGuardrailPolicy'](arg1);
}

export function UpdateTaskProtocolConfiguration(arg1) {
  return window['go']['main']['App']['UpdateTaskProtocolConfiguration'](arg1);
}

export function UpdateTaskStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTaskStatus'](arg1, arg2, arg3);
}

export function ValidateAIGeneratedCode(arg1) {
  return window['go']['main']['App']['ValidateAIGeneratedCode'](arg1);
}

export function ValidateAnalysisResults(arg1) {
  return window['go']['main']['App']['ValidateAnalysisResults'](arg1);
}

export function ValidateBudget(arg1, arg2) {
  return window['go']['main']['App']['ValidateBudget'](arg1, arg2);
}

export function ValidateEdits(arg1) {
  return window['go']['main']['App']['ValidateEdits'](arg1);
}

export function ValidatePath(arg1) {
  return window['go']['main']['App']['ValidatePath'](arg1);
}

export function ValidateProject(arg1, arg2) {
  return window['go']['main']['App']['ValidateProject'](arg1, arg2);
}

export function ValidateRepairRule(arg1) {
  return window['go']['main']['App']['ValidateRepairRule'](arg1);
}

export function ValidateSBOM(arg1, arg2) {
  return window['go']['main']['App']['ValidateSBOM'](arg1, arg2);
}

export function ValidateTaskProtocolStage(arg1, arg2) {
  return window['go']['main']['App']['ValidateTaskProtocolStage'](arg1, arg2);
}

export function ValidateTaskflow() {
  return window['go']['main']['App']['ValidateTaskflow']();
}

export function ValidateTestResults(arg1) {
  return window['go']['main']['App']['ValidateTestResults'](arg1);
}
