// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeTaskAndCollectContext(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnalyzeTaskAndCollectContext'](arg1, arg2, arg3);
}

export function CleanupTempFiles(arg1) {
  return window['go']['main']['App']['CleanupTempFiles'](arg1);
}

export function ExportContext(arg1) {
  return window['go']['main']['App']['ExportContext'](arg1);
}

export function GenerateCode(arg1, arg2) {
  return window['go']['main']['App']['GenerateCode'](arg1, arg2);
}

export function GenerateCodeWithOptions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateCodeWithOptions'](arg1, arg2, arg3);
}

export function GenerateIntelligentCode(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateIntelligentCode'](arg1, arg2, arg3);
}

export function GetFileContentAtCommit(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFileContentAtCommit'](arg1, arg2, arg3);
}

export function GetGitignoreContent(arg1) {
  return window['go']['main']['App']['GetGitignoreContent'](arg1);
}

export function GetProviderInfo() {
  return window['go']['main']['App']['GetProviderInfo']();
}

export function GetRichCommitHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetRichCommitHistory'](arg1, arg2, arg3);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetUncommittedFiles(arg1) {
  return window['go']['main']['App']['GetUncommittedFiles'](arg1);
}

export function IsGitAvailable() {
  return window['go']['main']['App']['IsGitAvailable']();
}

export function ListAvailableModels() {
  return window['go']['main']['App']['ListAvailableModels']();
}

export function ListFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2, arg3);
}

export function ReadFileContent(arg1, arg2) {
  return window['go']['main']['App']['ReadFileContent'](arg1, arg2);
}

export function RefreshAIModels(arg1, arg2) {
  return window['go']['main']['App']['RefreshAIModels'](arg1, arg2);
}

export function RequestShotgunContextGeneration(arg1, arg2) {
  return window['go']['main']['App']['RequestShotgunContextGeneration'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartFileWatcher(arg1) {
  return window['go']['main']['App']['StartFileWatcher'](arg1);
}

export function StopFileWatcher() {
  return window['go']['main']['App']['StopFileWatcher']();
}

export function SuggestContextFiles(arg1, arg2) {
  return window['go']['main']['App']['SuggestContextFiles'](arg1, arg2);
}

export function TestBackend(arg1, arg2) {
  return window['go']['main']['App']['TestBackend'](arg1, arg2);
}
