// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddBudgetPolicy(arg1:domain.BudgetPolicy):Promise<void>;

export function AddGuardrailPolicy(arg1:domain.GuardrailPolicy):Promise<void>;

export function AddRepairRule(arg1:domain.RepairRule):Promise<void>;

export function AnalyzeFile(arg1:string,arg2:string):Promise<domain.StaticAnalysisResult>;

export function AnalyzeGoProject(arg1:string):Promise<domain.StaticAnalysisResult>;

export function AnalyzeJavaScriptProject(arg1:string):Promise<domain.StaticAnalysisResult>;

export function AnalyzeProject(arg1:string,arg2:Array<string>):Promise<domain.StaticAnalysisReport>;

export function AnalyzeTaskAndCollectContext(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AnalyzeTypeScriptProject(arg1:string):Promise<domain.StaticAnalysisResult>;

export function ApplyEdits(arg1:domain.EditsJSON):Promise<Array<domain.ApplyResult>>;

export function ApplySingleEdit(arg1:domain.Edit):Promise<domain.ApplyResult>;

export function Build(arg1:string,arg2:string):Promise<domain.BuildResult>;

export function BuildAffectedGraph(arg1:Array<string>,arg2:string):Promise<domain.AffectedGraph>;

export function BuildAndTypeCheck(arg1:string,arg2:string):Promise<domain.BuildResult>;

export function BuildContext(arg1:string,arg2:Array<string>,arg3:string):Promise<string>;

export function BuildContextFromRequest(arg1:string,arg2:Array<string>,arg3:domain.ContextBuildOptions):Promise<domain.ContextSummary>;

export function BuildContextLegacy(arg1:string,arg2:Array<string>,arg3:string):Promise<string>;

export function BuildSymbolGraph(arg1:string,arg2:string):Promise<domain.SymbolGraph>;

export function CancelAutonomousTask(arg1:string):Promise<void>;

export function CleanupTempFiles(arg1:string):Promise<void>;

export function CloseStreamingContext(arg1:string):Promise<void>;

export function CreateStreamingContext(arg1:string,arg2:Array<string>,arg3:string):Promise<string>;

export function CreateTaskProtocolForProject(arg1:string,arg2:Array<string>):Promise<string>;

export function DeleteContext(arg1:string):Promise<void>;

export function DeleteReport(arg1:string):Promise<void>;

export function DeleteUXReport(arg1:string):Promise<void>;

export function DetectLanguages(arg1:string):Promise<Array<string>>;

export function DiscoverTests(arg1:string,arg2:string):Promise<domain.TestSuite>;

export function ExecuteRepair(arg1:string,arg2:string,arg3:string,arg4:number):Promise<domain.RepairResult>;

export function ExecuteTask(arg1:string):Promise<void>;

export function ExecuteTaskProtocol(arg1:string):Promise<string>;

export function ExecuteTaskflow():Promise<void>;

export function ExportContext(arg1:string):Promise<domain.ExportResult>;

export function ExportProject(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportReport(arg1:string,arg2:string):Promise<string>;

export function GenerateAndPublishDiff(arg1:string,arg2:string,arg3:domain.DiffFormat):Promise<domain.DiffResult>;

export function GenerateCode(arg1:string,arg2:string):Promise<string>;

export function GenerateCodeWithOptions(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GenerateComplianceReport(arg1:string,arg2:domain.ComplianceRequirements):Promise<domain.ComplianceReport>;

export function GenerateDerivedDiffReport(arg1:string,arg2:string,arg3:string):Promise<domain.DerivedDiffReport>;

export function GenerateDiff(arg1:string,arg2:string,arg3:domain.DiffFormat):Promise<domain.DiffResult>;

export function GenerateDiffFromEdits(arg1:domain.EditsJSON,arg2:domain.DiffFormat):Promise<domain.DiffResult>;

export function GenerateDiffFromResults(arg1:Array<domain.ApplyResult>,arg2:domain.DiffFormat):Promise<domain.DiffResult>;

export function GenerateIntelligentCode(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GeneratePerformanceMetrics(arg1:string):Promise<domain.PerformanceMetrics>;

export function GenerateReport(arg1:string,arg2:string):Promise<string>;

export function GenerateSBOM(arg1:string,arg2:domain.SBOMFormat):Promise<domain.SBOMResult>;

export function GenerateTimeToGreenMetrics(arg1:string):Promise<domain.TimeToGreenMetrics>;

export function GenerateWhyViewReport(arg1:string,arg2:Array<string>):Promise<domain.WhyViewReport>;

export function GetAutonomousTaskStatus(arg1:string):Promise<string>;

export function GetAvailableRepairRules(arg1:string):Promise<Array<domain.RepairRule>>;

export function GetBranches(arg1:string):Promise<string>;

export function GetBudgetPolicies():Promise<Array<domain.BudgetPolicy>>;

export function GetContext(arg1:string):Promise<string>;

export function GetContextContent(arg1:string,arg2:number,arg3:number):Promise<string>;

export function GetContextLines(arg1:string,arg2:number,arg3:number):Promise<string>;

export function GetCurrentBranch(arg1:string):Promise<string>;

export function GetCurrentDirectory():Promise<string>;

export function GetExportHistory(arg1:string):Promise<string>;

export function GetFileContentAtCommit(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetFileStats(arg1:string):Promise<string>;

export function GetGitignoreContent(arg1:string):Promise<string>;

export function GetGuardrailPolicies():Promise<Array<domain.GuardrailPolicy>>;

export function GetMetricsSummary():Promise<Record<string, any>>;

export function GetProjectContexts(arg1:string):Promise<string>;

export function GetProviderInfo():Promise<string>;

export function GetReadyTasks():Promise<Array<domain.Task>>;

export function GetReport(arg1:string):Promise<string>;

export function GetRichCommitHistory(arg1:string,arg2:string,arg3:number):Promise<Array<domain.CommitWithFiles>>;

export function GetSLAPolicy():Promise<string>;

export function GetSettings():Promise<domain.SettingsDTO>;

export function GetStreamingContext(arg1:string):Promise<string>;

export function GetSupportedAnalyzers():Promise<Array<domain.StaticAnalyzerType>>;

export function GetSupportedSBOMFormats():Promise<Array<domain.SBOMFormat>>;

export function GetSymbolDependencies(arg1:string,arg2:string,arg3:domain.SymbolGraph):Promise<Array<domain.SymbolNode>>;

export function GetSymbolDependents(arg1:string,arg2:string,arg3:domain.SymbolGraph):Promise<Array<domain.SymbolNode>>;

export function GetSymbolSuggestions(arg1:string,arg2:string,arg3:domain.SymbolGraph):Promise<Array<domain.SymbolNode>>;

export function GetTaskDependencies(arg1:string):Promise<Array<domain.Task>>;

export function GetTaskLogs(arg1:string):Promise<string>;

export function GetTaskProtocolConfiguration(arg1:string,arg2:Array<string>):Promise<string>;

export function GetTaskStatus(arg1:string):Promise<domain.TaskStatus>;

export function GetTaskflowProgress():Promise<number>;

export function GetUXReport(arg1:string):Promise<domain.UXReport>;

export function GetUXReports(arg1:domain.UXReportType):Promise<Array<domain.UXReport>>;

export function GetUncommittedFiles(arg1:string):Promise<Array<domain.FileStatus>>;

export function IsGitAvailable():Promise<boolean>;

export function ListAutonomousTasks(arg1:string):Promise<string>;

export function ListAvailableModels():Promise<Array<string>>;

export function ListFiles(arg1:string,arg2:boolean,arg3:boolean):Promise<Array<domain.FileNode>>;

export function ListReports(arg1:string):Promise<string>;

export function LoadTasks():Promise<Array<domain.Task>>;

export function PauseTask(arg1:string):Promise<void>;

export function PublishDiff(arg1:domain.DiffResult):Promise<void>;

export function ReadFileContent(arg1:string,arg2:string):Promise<string>;

export function RefreshAIModels(arg1:string,arg2:string):Promise<void>;

export function RemoveBudgetPolicy(arg1:string):Promise<void>;

export function RemoveGuardrailPolicy(arg1:string):Promise<void>;

export function RemoveRepairRule(arg1:string):Promise<void>;

export function RequestShotgunContextGeneration(arg1:string,arg2:Array<string>):Promise<void>;

export function RequestTaskProtocolCorrectionGuidance(arg1:string,arg2:string):Promise<string>;

export function ResetTaskflow():Promise<void>;

export function ResumeTask(arg1:string):Promise<void>;

export function RollbackEdits(arg1:Array<domain.ApplyResult>):Promise<void>;

export function RunIntegrationTests(arg1:string,arg2:string):Promise<Array<domain.TestResult>>;

export function RunSmokeTests(arg1:string,arg2:string):Promise<Array<domain.TestResult>>;

export function RunTargetedTests(arg1:domain.TestConfig,arg2:Array<string>):Promise<Array<domain.TestResult>>;

export function RunTests(arg1:domain.TestConfig):Promise<Array<domain.TestResult>>;

export function RunUnitTests(arg1:string,arg2:string):Promise<Array<domain.TestResult>>;

export function SaveSettings(arg1:string):Promise<void>;

export function SaveUXReport(arg1:domain.UXReport):Promise<void>;

export function ScanLicenses(arg1:string):Promise<domain.LicenseScanResult>;

export function ScanVulnerabilities(arg1:string):Promise<domain.VulnerabilityScanResult>;

export function SelectDirectory():Promise<string>;

export function SetSLAPolicy(arg1:string):Promise<void>;

export function StartAutonomousTask(arg1:string):Promise<string>;

export function StartFileWatcher(arg1:string):Promise<void>;

export function StopFileWatcher():Promise<void>;

export function SuggestContextFiles(arg1:string,arg2:Array<domain.FileNode>):Promise<Array<string>>;

export function TestBackend(arg1:string,arg2:string):Promise<string>;

export function TypeCheck(arg1:string,arg2:string):Promise<domain.TypeCheckResult>;

export function UpdateBudgetPolicy(arg1:domain.BudgetPolicy):Promise<void>;

export function UpdateGuardrailPolicy(arg1:domain.GuardrailPolicy):Promise<void>;

export function UpdateTaskProtocolConfiguration(arg1:string):Promise<void>;

export function UpdateTaskStatus(arg1:string,arg2:domain.TaskState,arg3:string):Promise<void>;

export function ValidateAIGeneratedCode(arg1:string):Promise<string>;

export function ValidateAnalysisResults(arg1:Record<string, domain.StaticAnalysisResult>):Promise<domain.StaticAnalysisValidationResult>;

export function ValidateBudget(arg1:domain.BudgetType,arg2:number):Promise<Array<domain.BudgetViolation>>;

export function ValidateEdits(arg1:domain.EditsJSON):Promise<void>;

export function ValidatePath(arg1:string):Promise<Array<domain.GuardrailViolation>>;

export function ValidateProject(arg1:string,arg2:Array<string>):Promise<domain.ProjectValidationResult>;

export function ValidateRepairRule(arg1:domain.RepairRule):Promise<void>;

export function ValidateSBOM(arg1:string,arg2:domain.SBOMFormat):Promise<void>;

export function ValidateTaskProtocolStage(arg1:string,arg2:string):Promise<string>;

export function ValidateTaskflow():Promise<void>;

export function ValidateTestResults(arg1:Array<domain.TestResult>):Promise<domain.TestValidationResult>;
