// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function GetCustomIgnoreRules():Promise<string>;

export function GetCustomPromptRules():Promise<string>;

export function ListFiles(arg1:string):Promise<Array<services.FileNode>>;

export function RequestShotgunContextGeneration(arg1:string,arg2:Array<string>):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetCustomIgnoreRules(arg1:string):Promise<void>;

export function SetCustomPromptRules(arg1:string):Promise<void>;

export function SetUseCustomIgnore(arg1:boolean):Promise<void>;

export function SetUseGitignore(arg1:boolean):Promise<void>;

export function SplitShotgunDiff(arg1:string,arg2:number):Promise<Array<string>>;

export function StartFileWatcher(arg1:string):Promise<void>;

export function StopFileWatcher():Promise<void>;
